import { Trash } from "lucide-react";
import {
  IconDashboard,
  IconUsers,
  IconSchool,
  IconCalendarCheck,
  IconCoin,
  IconEye,
  IconExams,
  IconHostel,
  IconTransport,
  IconPlacement,
  IconLibrary,
  IconReports,
  IconSettings,
  IconSearch,
  IconBell,
  IconPlus,
  IconDownload,
  IconFilter,
  IconEdit,
  IconTrash,
  IconCheck,
  IconX,
  IconMap,
  IconAward,
  IconMail,
  IconUsersGroup,
  IconCalculator,
  IconGradCap,
  IconFlask,
  IconLedger,
  IconStar,
  IconUpload,
  IconCamera,
  IconLock,
  IconHistory,
  IconRupee,
  IconAlertCircle
} from "../../../components/Icons";



/* ════════════════════════════════════════
   IC MAP — every key is unique
════════════════════════════════════════ */
export const IC = {
  Dashboard: <IconDashboard />,
  Students: <IconUsers />,
  Faculty: <IconSchool />,
  Attendance: <IconCalendarCheck />,
  Exams: <IconExams />,
  Fees: <IconCoin />,
  Hostel: <IconHostel />,
  Transport: <IconTransport />,
  Placement: <IconPlacement />,
  Library: <IconLibrary />,
  Reports: <IconReports />,
  Settings: <IconSettings />,
  Search: <IconSearch />,
  Bell: <IconBell />,
  Plus: <IconPlus />,
  Download: <IconDownload />,
  Filter: <IconFilter />,
  Edit: <IconEdit />,
  Trash: <IconTrash />,
  Check: <IconCheck />,
  X: <IconX />,
  Eye: <IconEye />,
  Map: <IconMap />,
  Award: <IconAward />,
  Mail: <IconMail />,
  UsersGroup: <IconUsersGroup />,
  Calculator: <IconCalculator />,
  GradCap: <IconGradCap />,
  Flask: <IconFlask />,
  Ledger: <IconLedger />,
  Trash: <IconTrash />,
  Upload: <IconUpload />,
  Camera: <IconCamera />,
  Lock: <IconLock />,
  History: <IconHistory />,
  Rupee: <IconRupee />,
  Star: <IconStar />,
  AlertCircle: <IconAlertCircle />,
  CalendarCheck: <IconCalendarCheck />,
}